import { Route, Routes, Navigate, HashRouter } from "react-router-dom";
import './App.css'

import Navigation from './routes/navigation.tsx'
import Report from './routes/report.tsx'

import type { ReportType } from './types/report.tsx'

import autonomousMoonRover from './assets/autonomousMoonRover.png';

function App() 
{
  

  const notFoundWorkTermTitle:string = "Co-op position not secured yet"
  const incompleteWorkTermReport:ReportType = [{text: "This co-op is still ongoing. The report will be posted once the work term is completed"}];

  const workTerm1:ReportType = 
  [
    {text: "From May 27th to August 22nd, 2025, I worked as a STEAM Instructor at The STEAM Project for my first co-op work term. I was responsible for creating lesson plans during June and then leading those lessons in July and August to a group of roughly fifteen 7-year-olds. Throughout this report, I will walk through my experiences, takeaways and highlight why both camp and teaching experience are so valuable to developing crucial workplace skills."},
    {text: "The STEAM Project is a Science, Engineering, Engineering, Art, and Math focused summer camp that has been running in Richmond Hill for the past 10 years. The STEAM Project stands out from other camps due to its emphasis on learning during each activity. Regarding technology, The STEAM Project uses different robots called mbots, and micro:bits to teach campers how to program with block coding. The STEAM Project also uses 3D Printing and Laser Cutting to manufacture many interesting and unique projects.  As an instructor at The STEAM Project, I reported directly to the Program Manager who is responsible for managing all instructors, and projects that are created. The Program Manager then reports to the Camp Director who oversees one of five sites. Finally, the Camp Director reports to Jay, the CEO of The STEAM Project."},
    {text: "Going into this role I had three major goals. My first goal was to develop a bond which each camper that I taught. This was so that I could tailor each lesson and my teaching style towards them to ensure they’re enjoying learning. I made sure to reach this goal by first speaking to each camper individually to learn their names and something about them. From there I continued to bond with them throughout the session. For example, during one session I noticed many of the campers were very engaged with the lesson portion of the activity. This led me to ask them more open-ended questions during the lesson portion to allow them to guess what certain concepts mean before I introduce them.  This resulted in the campers being excited to learn, and not afraid to ask for help when needed. Through this, I also developed my communication skills and learnt how to adapt to working with people with different needs. "},
    {image: autonomousMoonRover, alt: "Block coding block that follows the logic of 'forever, if there's an obstacle ahead, light up red and turn left. If there's an obstacles ahead light up red and turn right. Otherwise move forward", text: "My second goal was to design my own coding projects, as I wanted to learn how to apply my programming knowledge to communicate foundational concepts in an easy-to-understand way. I achieved this with two major projects. The first one was called Autonomous Moon Rover. This project utilized block coding and robots that had the capability to move and detect objects in front of it. One concept at a time, I taught campers about basic move commands, if statements, and loops. The result was a robot that is programmed to solve a maze by either going forward, left, or right based on if there is an obstacle in front of it. My second project was called Build a Tree. This project used block coding to control a robot with a light sensor, and an LED matrix. The project was an old project that was used in 2023 and consisted of a simple tree growing animation using the LEDs. I decided to use the light sensor to simulate a tree that doesn’t get enough light, while also teaching the campers more about programming control flow. If the light level is above a certain threshold, it will play the original tree-growing animation. If not, it will only play the first frame of the animation. After running these projects, the campers understood the programs they were building and had a firm grasp on fundamental coding principles."},
    {text: "My third goal was to take on a leadership role throughout the summer because I wanted to demonstrate initiative and take on new challenges. I did my best to take every opportunity I was given to take more responsibility. For example, at the beginning of each day, a camp-wide ten-minute activity called a flagpole is run. I volunteered to help plan and run many of the flagpoles including games, theme-day skits, and songs. I also always made sure to always have backup flagpoles to ensure that if we didn’t have one planned, we would still be able to run something interesting. I also made sure to participate for many of the optional camp activities such as water days, staff challenges, and even singing a site-wide cheer. As a result, I learnt the importance of taking the initiative at work so that I can both help my colleagues succeed and improve my own skills."},
    {text: "In June, I worked with a team of instructors, and my Program Manager to develop the activities for the summer. We helped each other create the projects and held group brainstorms to generate new ideas. This time taught me how to work in a team in a professional environment and support my colleagues. By the time camp started, and the campers started showing up we still had almost a quarter of projects left to plan. This led to us adapting our strategy to ensure all projects could be completed in time. Instead of spending time developing new projects, we put most of our efforts into modifying older projects. This removed the time taken for brainstorming and gave us a working project to start from. To complete each project, we would understand how it works, look at feedback from when it was previously run, and then implement the feedback to ensure the finished project is as good as it possibly can. This shift in strategy allowed us to complete all projects well before the deadline."},
    {text: "In July and August, I taught three unique hour-long lessons each day.  In-between each of the lessons we had some time to complete reflections and learn future lessons. We needed to use our time-management skills to ensure that we had learnt and internalized each lesson at a level that we could teach it. Doing this each day improved my ability to take in and learn new information quickly. We also needed to use our organizational skills to ensure that we had all the required materials for each project, and we knew where each material was. Teaching the lessons itself also improved my ability to explain complex topics in simple terms as we often taught lessons on topics such as atoms, molecules, and different engineering concepts. "},
    {text: "I would like to take this paragraph to acknowledge my direct supervisor and Program Manager, Brandon Cusato as well as the Camp Director Rachel Kaunismaa for supporting me while I was an instructor. Brandon always went out of his way to ensure I had everything I needed to succeed, assisted me and the other instructors in any way that he could, and always had a positive attitude, even when we were behind schedule on projects. Rachel made sure everything was running smoothly, was very accommodating of me, and always brought a positive energy to camp."},
    {text: "My time working as an Instructor at The STEAM Project taught me many valuable skills I will take with me throughout my career. I learnt how to effectively work as a team, adapt to changing situations, take initiative, communicate with others, manage my time, and explain complex concepts in simple terms."},
  ];

  const workTerm2:ReportType = 
  [
    {text: "During the fall semester of 2025, I worked as a Business Intelligence Intern at The Co-operators. This was my second co-op term and my first experience in the corporate world. I had the opportunity to see how data is used, organized, and managed at a large scale. Throughout this report, I’ll walk through my experiences, what I learned, and how this role helped me develop the necessary skills I need to succeed in my professional career."},
    {text: "The Co-operators is an insurance co-operative, which means the business is democratically controlled by its members instead of outside investors, and their main goal is to meet the needs of its members rather than maximize profits for shareholders. In my team, there are three different types of roles, and we all reported directly to Lina, our manager.  Data analysts work with the business to determine the exact requirements for our team and create dashboards for reporting purposes. Developers are responsible for managing the code relating to the reporting system. Finally, there are data integration specialists. This is the role that I filled, and consists of adding features, managing the codebase, and responding to tickets relating to the database."},
    {text: "At the beginning of this work term, I created three learning goals. My first goal was to improve my understanding of database design. I wanted to understand the purpose of each step in the object layer, and why different decisions were made during its development. I wanted to focus on gaining an understanding of the choices and the impact of lower-level decisions that were made when the database was designed. The reason I wanted to achieve this goal is because I find that I work at my best when I have a thorough understanding of the system that I am working with. Since then, I had the opportunity to work with and become familiarized with many other parts of the database. For example, I improved my understanding of the process where we take the source data and transform it into our primary fact table. I was able to learn this through changing features and debugging many issues code related issues. Despite this, there are still parts of the database I have not seen and have the opportunity to learn more about during my next work term."},
    {text: "My second goal was to improve my ability to ask questions. In my last co-op term, the biggest piece of feedback I received was that I asked too many questions, especially pertaining to things I was confident about, but not certain. I wanted to work on being more independent and not asking as many questions, while still asking questions when needed. I also wanted to increase the quality of my questions through never asking the same question twice. Throughout this work term, I have made great improvements in this area. Whenever asking questions I make sure they’re thoughtful and often give my thought process in the question itself. I’ve also avoided asking repeat questions by taking notes whenever I ask for help, so I have something to come back to if I forget the answer. "},
    {text: "My final goal was to improve my ability to independently develop effective solutions to problems. I was comfortable diagnosing problems and modifying existing solutions, but I relied on discussing these ideas with coworkers. I wanted to focus on building the skills needed to design and develop solutions. Since then, I’ve worked on developing solutions to many different problems I have faced. Most solutions that I developed were a result of speaking with someone else about the best high-level approach, then creating the steps to implement the solution, and finally developing it. I am happy with this as collaborating on the approach to a solution ensures the quality of the solution is still high and I am making less mistakes. For example, I discussed the requirements of a warning system with my mentor that we wanted to put in place. I designed the stored procedure, table, and developed the code myself before passing it back for review and implementation."},
    {text: "The general flow of the position was organized through our Jira board. Through the board, we were assigned different tasks, where we would manage our time, and prioritize what we were given. To help with this, we had biweekly scrums and monthly tasks to make the team aware of what we were working on, and any blockers we were experiencing. We were given many different tasks, most of which involved improving the database in some way, either by adding a new column or changing some stored procedure. This requires the ability to translate function requirements into real SQL code. It taught me the importance of quality code that is easily understandable and adheres to the standard of the rest of the codebase. I learnt the importance of rigorous testing to ensure any bugs are caught before being deployed to production. I also learnt how to code in a team and collaborative setting, while using git to ensure proper version control. Other tasks we were given involved responding to user support tickets to fix an issue found in the database. It was important to find a long-term solution instead of a band-aid fix. This requires a lot of time management skills as each ticket is time sensitive and needs to be solved as soon as possible. I learnt how to prioritize my time in an environment with constantly switching priorities. When I initially joined the team, we were already short staffed, along with my onboarding mentor set to leave the company in a few weeks. I further developed my ability to learn, internalize, and apply information fast, and I was able to contribute at full capacity within a few weeks. During this onboarding period, I found that there wasn’t a specific piece of documentation that outlined the structure of the database. I worked to create a document that outlines all this information, which has since been made available to the rest of the team. I was pleased to see a new hire in mid-November found my documentation valuable and helped them get up to speed quickly."},
    {text: "I would like to take this paragraph to acknowledge my supervisor and my mentors throughout this work term. First, I’d like to thank my manager Lina Lee for supporting me throughout my work term, making sure I wasn’t overwhelmed with work, and ensuring I had everything I needed to succeed. I’d also like to thank my original mentor, Neeraj Bhanot for supporting me through my onboarding experience and teaching me everything I needed to know about the insurance industry, and the technical aspects of the role. Finally, I’d like to thank my other mentor, Enilton Machado for helping me work through problems when I’m struggling, and for peer reviewing all my PR’s and backfill requests."},
    {text: "My time as a Business Intelligence Intern taught me many valuable skills that I will take with me throughout the rest of my professional career. I improved my time and priority management skills, my ability to learn and apply information fast, and greatly improved my problem-solving skills. I’ve also developed my ability to create high quality code, test thoroughly, and use version management software to code collaboratively. Through all my hard work and dedication in this role, I have received great feedback and was even nominated for the 2025 Co-op Student of the Year Award! I’m excited to announce that I will be returning to The Co-operators as a Business Intelligence Intern during the summer of 2026!"}
  ];


  return (
    <HashRouter>
      <Routes>
          <Route path="/" element={<Navigation/>}>
            <Route index element={<Navigate to="workterm1" replace />} />
            <Route path="workterm1" element={<Report title="STEAM Instructor at The STEAM Project" content={workTerm1}/>}/>
            <Route path="workterm2" element={<Report title="Business Intelligence Internship at The Co-operators" content={workTerm2}/>}/>
            <Route path="workterm3" element={<Report title="Business Intelligence Internship at The Co-operators" content={incompleteWorkTermReport} />}/>
            <Route path="workterm4" element={<Report title={notFoundWorkTermTitle} />}/>
            <Route path="workterm5" element={<Report title={notFoundWorkTermTitle} />}/>
          </Route>
      </Routes>
    </HashRouter>
  )
}

export default App
